// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeShare.Data;

#nullable disable

namespace RecipeShare.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RecipeShare.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Pasta",
                            CookingTimeMinutes = 25,
                            DateCreated = new DateTime(2025, 5, 15, 22, 30, 34, 987, DateTimeKind.Local).AddTicks(2397),
                            Description = "A classic Italian pasta dish with eggs, cheese, pancetta and black pepper.",
                            Difficulty = 1,
                            ImageUrl = "/images/carbonara.jpg",
                            Ingredients = "400g spaghetti, 200g pancetta, 3 large eggs, 75g Pecorino Romano cheese, 50g Parmesan, black pepper",
                            Instructions = "1. Cook pasta until al dente.\n2. Fry pancetta until crisp.\n3. Beat eggs with cheese and pepper.\n4. Mix everything together off the heat.",
                            Title = "Spaghetti Carbonara"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Breakfast",
                            CookingTimeMinutes = 10,
                            DateCreated = new DateTime(2025, 5, 15, 22, 30, 34, 987, DateTimeKind.Local).AddTicks(2424),
                            Description = "Simple and nutritious breakfast option that's ready in minutes.",
                            Difficulty = 0,
                            ImageUrl = "/images/avocado-toast.jpg",
                            Ingredients = "2 slices of bread, 1 ripe avocado, lemon juice, salt, pepper, red pepper flakes",
                            Instructions = "1. Toast bread until golden.\n2. Mash avocado with lemon juice, salt and pepper.\n3. Spread on toast and sprinkle with red pepper flakes.",
                            Title = "Avocado Toast"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dessert",
                            CookingTimeMinutes = 25,
                            DateCreated = new DateTime(2025, 5, 15, 22, 30, 34, 987, DateTimeKind.Local).AddTicks(2427),
                            Description = "Classic homemade cookies that are crisp on the outside and chewy in the middle.",
                            Difficulty = 0,
                            ImageUrl = "/images/cookies.jpg",
                            Ingredients = "250g flour, 1/2 tsp baking soda, 170g melted butter, 100g white sugar, 200g brown sugar, 1 tsp vanilla, 1 egg, 1 egg yolk, 200g chocolate chips",
                            Instructions = "1. Mix dry ingredients.\n2. Cream butter and sugars, add eggs and vanilla.\n3. Combine with dry ingredients and fold in chocolate chips.\n4. Bake at 325°F for 15 minutes.",
                            Title = "Chocolate Chip Cookies"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
